### ISSUE TITLE
Check the module version before using the SSL connectivity

### ISSUE THREAD

**Issue by ostaquet** [ostaquet/Arduino-SIM800L-driver#11]
According to some tests and issues  (#10 and https://github.com/vshymanskyy/TinyGSM/issues/29), the version 13.08 doesn't support SSL connectivity.

In order to avoid troubles in the future, add the check before trying to establish a communication.

Seems that SSL feature is available only since v14 of the module.

**Comment by andrewstillie** [comment]
I am using a TTGO-Tcall module.  I am using the Arduino ecosystem to write my code with 
TinyGsm
TinyGsmClient
HttpClient

How can I request the SIM800 version number?

**Comment by ostaquet** [comment]
You can install the last version of the library and run the BasicTest example ;-)

**Comment by andrewstillie** [comment]
Thank You - I can see I have SIM800 R14.18
How do I activate SSL for my POST to AWS API Gateway?

**Comment by ostaquet** [comment]
Did you already try the examples provided with the library? (see [HTTPS_POST_HardwareSerial](https://github.com/ostaquet/Arduino-SIM800L-driver/blob/master/examples/HTTPS_POST_HardwareSerial/HTTPS_POST_HardwareSerial.ino))

You may encounter some security issues as the SIM800L is not so recent and doesn't support the latest SSL security layers (like some 605 or 606 errors as documented in the [SSL application notes](https://github.com/ostaquet/Arduino-SIM800L-driver/blob/master/extras/SIM800%20Series_SSL_Application%20Note_V1.00.pdf))

**Comment by ostaquet** [comment]
Issue fixed with release 1.11.0
