### ISSUE TITLE
how send var using get?

### ISSUE THREAD

**Issue by primayanuaristya** [ostaquet/Arduino-SIM800L-driver#13]
For example send 'acak'
```
 gsm.println("AT+HTTPINIT");
  toSerial();
  delay(1000);
  int acak = random(11111, 99999);

  //masukan url website
  gsm.print("AT+HTTPPARA=\"URL\",\"http://iot.mywebsite.com/sim800/get.php?val=" + String(acak) + "&");
  gsm.println("\"");
  toSerial();
  delay(1000);
```

**Comment by primayanuaristya** [comment]
i hope can using it
sim800l->doGet("https://postman-echo.com/get?foo1=bar1&foo2=bar2", 10000);
and bar1 and bar2 change to example read sensor.

**Comment by ostaquet** [comment]
I don't see any issue by using the variables directly in the URL.

Did you already try?

If yes and didn't work, can you post the debug console?
