### ISSUE TITLE
Software serial wrong delcaration?

### ISSUE THREAD

**Issue by TheEngineersCorner** [ostaquet/Arduino-SIM800L-driver#21]
hello, the basic test for software serial is incorrect? the rx and tx is wrong way.

SoftwareSerial(SIM800_TX_PIN, SIM800_RX_PIN);
The correct method is:
SoftwareSerial(RX,TX)

See, https://www.arduino.cc/en/Tutorial/SoftwareSerialExample

**Comment by mohammadfatemieh** [comment]
It's not different because the RX pin and TX pin is defined

#define SIM800_TX_PIN 3
#define SIM800_RX_PIN 2
#define SIM800_RST_PIN 6

**Comment by mohammadfatemieh** [comment]
I think You say correctly

**Comment by ostaquet** [comment]
You right, to me clean. I should invert the names.

But at the end, the TX pin of the SIM800 is connected on the RX pin of the Arduino and the RX pin of the SIM800 is connected on the TX pin of the Arduino :-P

Fixed in master branch.

Thanks for the feedback
