### ISSUE TITLE
Access to low level functions to communicate with the SIM800L module

### ISSUE THREAD

**Issue by Creyesb28** [ostaquet/Arduino-SIM800L-driver#22]
Hello Ostaquet, I would like to make use of the low-level functions to be able to consult the location provided by the sim with the command AT + CIPGSMLOC = 1,1 or with the command AT + CLBS = 1,1.

I see that they are in the .cpp of the library but when implementing them it does not work for me, in the following image i show you what's says the arduino IDE 

On the other hand, if I want to use the library and I have a PHP base application, can I use the post you have there or would it only be useful for Postman?

THANKS ! 

![image](https://user-images.githubusercontent.com/64244784/92196957-0e131e00-ee36-11ea-86cf-e200c1e7659f.png)

**Comment by ostaquet** [comment]
This is C++ language related, not an issue in the library ;-).

The low-level functions are defined as protected; meaning that you cannot access those functions directly outside of the class or a class with inheritance of this class.

Check out [C++ Access Specifiers](https://www.w3schools.com/cpp/cpp_access_specifiers.asp) for more info.

To access to this low-level function, you can:
1. Change the access specifier to `public`
2. Make an inherited class of `SIM800L` and override the access specifier
