### ISSUE TITLE
HTTP GET time out

### ISSUE THREAD

**Issue by smshariatzadeh** [ostaquet/Arduino-SIM800L-driver#24]
The HTTP GET may suspend the application, If there is a problem with the HTTP page(for example bad ending), 
So, is it possible to define HTTP GET time out in order to prevent program suspension?

**Comment by ostaquet** [comment]
When you call the method `doGet()`, you are able to define the parameter `serverReadTimeoutMs` which is the timeout in milli-sec.

For the `doPost()` method, you are able to define the parameters `clientWriteTimeoutMs` and the `serverReadTimeoutMs`.
