### ISSUE TITLE
URL is of Const Char Type. I want to Send a Sensor Value so it Can't be Constant. HELP!!

### ISSUE THREAD

**Issue by Kartikeyanand03** [ostaquet/Arduino-SIM800L-driver#26]

**Comment by ostaquet** [comment]
Hi @Kartikeyanand03,

Can you be more specific about what you aim to achieve?

The sensor values can be sent via the POST method and adding the data in the payload.

KR,
Olivier

**Comment by Kartikeyanand03** [comment]
I'm able to send the Data Now by post. But the GPS is unable to read. Only 1 Serial is Working

**Comment by ostaquet** [comment]
😅 Sorry but without any details and background, it is very hard to help.

**Comment by ostaquet** [comment]
Without any additional information, it is difficult to provide guidance :-/
