### ISSUE TITLE
Data size overflow

### ISSUE THREAD

**Issue by nitko12** [ostaquet/Arduino-SIM800L-driver#27]
Hi, 

shouldn't this be of some larger data type, in case of larger requests?

https://github.com/ostaquet/Arduino-SIM800L-driver/blob/34e6fc6c44186a31eef6932b1b483b1dff0fae99/src/SIM800L.cpp#L479

**Comment by ostaquet** [comment]
Well done!

Indeed the `dataSize` is a `uint16_t`.

Fixed in v1.13.1

Thanks for noticing 👍
