### ISSUE TITLE
How to set variables in URL?

### ISSUE THREAD

**Issue by hasantunacoder** [ostaquet/Arduino-SIM800L-driver#32]
thank you very much for this code. it is working very well. But i dont know , how can i  HTTP GET variables?
can i do it? 

char URLGet[] = "http://hasantuna.com/read.php/get?value1=123&value2=212";

but value1 and value2 are variables and how can i use it?
thanks , best regards.

**Comment by ostaquet** [comment]
The URL are defined as `char *`. So, you are able to compose your own URL according to your needs.

The easiest way to do it is to use a buffer (i.e. `URLGet`) and compose it with a standard function like `sprintf()`.

By example:
```
// Define variable to receive the final char array
char URLGet[80];

// Values to be integrated
int value1 = 123;
int value2 = 212;

// Replace %d by values as arguments
sprintf(URLGet, "http://hasantuna.com/read.php/get?value1=%d&value2=%d", value1, value2);

Serial.println(URLGet);
```

You will find plenty of information about how to format char array with the `sprintf()` function.
