### ISSUE TITLE
sim800l->doPost Limit Size 

### ISSUE THREAD

**Issue by lasida** [ostaquet/Arduino-SIM800L-driver#34]
Hi. 

i use this library and it works fine. the function of sim800l->doPost is using data type char for sending the payload, and in esp32 limit char is 4000bytes, can I send 25.000 bytes of data json in one post, or I must split the json to post the data,

I was using String type data for handle the 25.000 bytes of data, but it can't fit to functions sim800l->doPost.

maybe you have a suggestion
Thanks :D

**Comment by bhupiister** [comment]
@lasida any luck? I want to send log file via post method. Do you think it's possible?

**Comment by lasida** [comment]
yes, it's possible in ESP32, I sending 21100bytes, or 21.1 kB data of JSON with base64image string
I just create char jsonVision[30000] outside the loop before setup(). and wrapping with library ArduinoJson 
the problem is, you create a char variable inside the loop, it will be 4000bytes only.

And using SpiRamAllocator for increasing JsonDocument
https://arduinojson.org/v6/how-to/use-external-ram-on-esp32/

Before I using SpiRamAllocator its just 8.8kB data received.
I think it's limit JsonDocument default from ArduinoJson Lib
