### ISSUE TITLE
Multiline responses from server suspends doGet() and doPost() procedures

### ISSUE THREAD

**Issue by vosmarsk** [ostaquet/Arduino-SIM800L-driver#36]
I tried examples from the library. I want to use it in a simple IoT device.
Everything works fine as long as the server sends a one-line response.
However, if it sends more lines, the program stops working after the AT_CMD_HTTPREAD command.

I found the problem in lines :
        // If the character is CR or LF, ignore it (it's probably part of the module communication schema)
        if((recvBuffer[i] == '\r') || (recvBuffer[i] == '\n')) {
          i--;
        }

index decrementing causing that index never reach dataSize value and program stay cycling in  
while(!stream->available());
that is empty

After comenting these lines works all right. I think is not need to remove these chars or empty lines. They can be removed later if needed. 
Otherwise nice work. Thank you.

**Comment by ostaquet** [comment]
Fixed in release https://github.com/ostaquet/Arduino-SIM800L-driver/releases/tag/1.14.0.

Thanks for noticing!
