### ISSUE TITLE
doGet(): just write without reading?

### ISSUE THREAD

**Issue by TexhFex** [ostaquet/Arduino-SIM800L-driver#39]
Hello,

I think I have a simple question:

Is it possible to call a website but not to read it out? (Just open it)
(In order to save data volume)

Thanks in advance

TexhFex

**Comment by ostaquet** [comment]
Hi @TexhFex 

If you want to save data volume, the best is to design the website to limit the data to be sent. As the library is using the network stack of the SIM800L, the HTTP GET operation is always followed by the reading of the data.

It means that:
1. Your code is calling `doGet()` in the library
2. The library set up the module to start the HTTP GET.
3. The library requests the module to perform the GET.
4. The module send the GET request and wait.
5. The module receives the GET answer and inform the library that it is ready.
6. The library reads the data from the module.
7. Your code is reading the data from the library.

I don't think you could reject the descending data stream from the server to save data volume.

So, the best is to design the website (or use a specific URL) to send back as little data as possible.
