### ISSUE TITLE
I tried with SIM800L with ESP32 but getting (Guru Meditation Error: Core  1 panic'ed (IllegalInstruction). Exception was unhandled. Memory dump at 0x400d0e74: ffffffff ffffffff ffffffff)

### ISSUE THREAD

**Issue by sanjeemax** [ostaquet/Arduino-SIM800L-driver#40]

**Comment by ostaquet** [comment]
HI @sanjeemax 
Can you add some logging and information about when it is happening?

As I saw there is a memory dump. So, I guess it is during execution and not compilation. Can you confirm?
