### ISSUE TITLE
Library works fine with my nodemcu, how to sendSMS using this Library

### ISSUE THREAD

**Issue by printing88** [ostaquet/Arduino-SIM800L-driver#43]
, this is the only library that works with my ESP8266 without a boot problem, how do i add a function to send sms??

**Comment by ostaquet** [comment]
Hi,

This library is not intended to support sending and receiving SMS. That's why the name of the library is `SIM800L HTTP connector` but I admit that the repository name could be confusing ;-)

KR,
Olivier
