### ISSUE TITLE
Gprs connection credentials

### ISSUE THREAD

**Issue by trdb33** [ostaquet/Arduino-SIM800L-driver#44]
Hey, I'm playing with the library and I can't connect because there is missing 2 values in the library, my isp is using apn, user and password
My question is how I can add USR and PWD to gprs connection ?
Thanks

**Comment by ostaquet** [comment]
The fix has been merged in the master branch.
It will be available in the next release (probably later today).

**Comment by ostaquet** [comment]
The fix is available in version 1.13.3 ;-)
