### ISSUE TITLE
Getting 703 error, but still HTTP Post is successful if gprs is not disconnected.

### ISSUE THREAD

**Issue by rahul121190** [ostaquet/Arduino-SIM800L-driver#46]
Hi,
I was using the sim800L library and it was going all well. Since last week, the return value for most of the HTTP Posts (doPost) was 703 (Unable to initiate HTTP Post). However if I do not disconnect GPRS after the failure, or have a delay before disconnecting the GPRS, the HTTP Post is successful. (I am able to see the request in my AWS log).

Even though the Http post is initiated, I am getting 703 as the response to the doPost method. I tried changing the timeout to 10/15 seconds.

**Comment by ostaquet** [comment]
Hi @rahul121190,

Which version are you using?

Can you test the version 1.13.3 and 1.14.0 and share the results?

KR
