### ISSUE TITLE
Incorrect Serial initialization

### ISSUE THREAD

**Issue by ZJouba** [ostaquet/Arduino-SIM800L-driver#47]
https://github.com/ostaquet/Arduino-SIM800L-driver/blob/e63963c9c0bb2c25e5d80a0822fbc5050e076784/examples/HTTPS_POST_SoftSerial/HTTPS_POST_SoftSerial.ino#L50

TX should be first then RX

**Comment by ostaquet** [comment]
Already discussed in #21
