### ISSUE TITLE
MQTT protocol implementation

### ISSUE THREAD

**Issue by ostaquet** [ostaquet/Arduino-SIM800L-driver#5]
Hi Olive! Yes! Is compiling with no problem! Amazing! 

Now the issue is my SIM800L hahaha, but i will figure out what's is going on!

Again, thank you very much mate!

Just a suggestion: Could you try to work with MQTT protocol?

Cheers!

_Originally posted by @grfbr in https://github.com/ostaquet/Arduino-SIM800L-driver/issues/3#issuecomment-525107454_

**Comment by ostaquet** [comment]
Hi,
At the moment, there is no plan to implement MQTT protocol in the driver. I took good note of your suggestion ;-)
KR

**Comment by ankitmhatre** [comment]
Hey @ostaquet, I think it is already a high time for having few MQTT functions.

**Comment by ostaquet** [comment]
Hi @ankitmhatre, you are free to contribute ;-). There are some ideas to implement it in issue #30.

**Comment by ostaquet** [comment]
As mentioned in the README, the project is no longer maintained as my module is broken. Thanks for reporting the issue.
