### ISSUE TITLE
getSimCardNumber into a variable

### ISSUE THREAD

**Issue by ZJouba** [ostaquet/Arduino-SIM800L-driver#50]
Hi there, I'm trying to do the following:
```
void generatePayload(char * coordinates, char * payload)
{
  sprintf(payload, "{\"sn\":\"%s\", ", getImeiNum());
  ...
}
char* getImeiNum()
{
  char* imei = sim->getSimCardNumber();
  delay(100);
  return imei;
}
```
And it does execute the command on the module and return the ID but when I print the payload it is blank
```
Generating payload
SIM800L : Send "AT+CCID"
SIM800L : End of transmission
SIM800L : Receive "AT+CCID
89354600000001419885

{"sn":"", 
```

I hope you can help me. Thank you

**Comment by ostaquet** [comment]
The function ```getSimCardNumber()```is returning a pointer to a buffer used by the library. This buffer is used by multiple functions in the library as a shared buffer. If you want to make a specific usage of the SIM card number, you should make a copy (```memcpy()```).

Be sure also that you're receiving correctly the char array pointer by ```printf()``` the value just after the call (or through the call) to ```getSimCardNumber()```.
