### ISSUE TITLE
Dynamic Allocation of data to the payload(in this case, a json string)

### ISSUE THREAD

**Issue by Kobemash** [ostaquet/Arduino-SIM800L-driver#54]
I am reading sensor data and it is being periodically posted to a server after 15 minutes. The challenge I am encountering is how to dynamically initialise a JSON object to the PAYLOAD considering the PAYLOAD has to be initialised during setup and it is declared as a const char array.

**Comment by ostaquet** [comment]
As mentioned in the README, the project is no longer maintained as my module is broken. Thanks for reporting the issue.
