### ISSUE TITLE
Support other modules e.g. SIM7070G or SIM7600E

### ISSUE THREAD

**Issue by reinos** [ostaquet/Arduino-SIM800L-driver#57]
Hi there,

First of all, great library!

Currently im working with a sim800L but Im upgrading the module to a different one SIM7070G or SIM7600E. Does the library also support other modules other than the SIM800L?

let me know.

**Comment by ostaquet** [comment]
No idea if it is compatible. I guess that SimCom offers the same AT commands on the new version than on the SIM800L. You should check the AT commands guide, compare the format/commands used in the library and adapt if required.
