### ISSUE TITLE
after update getSignal() return zero and block module to connect 

### ISSUE THREAD

**Issue by becher** [ostaquet/Arduino-SIM800L-driver#62]
please fix this code
```

 int16_t idxBase = strIndex(internalBuffer, "AT+CSQ");
    if(idxBase != 0) {
      return 0;
    }
```

solution  : 

```
 int16_t idxBase = strIndex(internalBuffer, "+CSQ: ");
    if(idxBase < 0) {
      return 0;
    }
```

is worked for me :)

**Comment by ostaquet** [comment]
I saw some issues lately like this one. It seems that SIMCom changed some AT answers.

Thanks for the fix!

Can you tell me the hardware you're using and the firmware version?

**Comment by ostaquet** [comment]
As mentioned in the README, the project is no longer maintained as my module is broken. Thanks for reporting the issue.
