### ISSUE TITLE
Sim800l restarts after gprs connected checking

### ISSUE THREAD

**Issue by vnariman** [ostaquet/Arduino-SIM800L-driver#64]
Sim800l module (red module) restarts when checking is net connected and try to restart self continuously when red led blinks fast means gprs is connected. Why?

im using Sim800l with arduino nano (ft232) with 3300uf on power pins, lm2596 module for power supply (fix on 4.1v), all wires less than 10cm.

im marked senddata functions last while(1) row but still repeats restarting after checking net connected or not.

**Comment by ostaquet** [comment]
It seems that your problem is linked to power supply. The module is consuming significant power when establishing the connectivity. This is more an hardware/schematics issue and it is not related to the code.
