### ISSUE TITLE
Still alive?

### ISSUE THREAD

**Issue by chrishubert** [ostaquet/Arduino-SIM800L-driver#66]
Hello @ostaquet.
Thanks a lot for your library. It solved many memory issues that I had while trying to handle the AT commands myself.

I would like to push some new functionalities (especially IP resolving), are you still accepting PR?

**Comment by ostaquet** [comment]
Hi @chrishubert 
Unfortunately, this project is no longer maintained. I tried today to build and fix some issues but my module is broken.
Feel free to fork the project.
KR
