### ISSUE TITLE
Relatively smallest internal buffer size for get

### ISSUE THREAD

**Issue by PeterBasista** [ostaquet/Arduino-SIM800L-driver#8]
This is not issue and rather a question. Apparently, the doGet function uses a pointer instead of copying the entire field. For doPost, it is necessary to set a large enough internal buffer for Url. What is the smallest internal buffer size when using doGet ()? The default value in the constructor is 128 but that is quite a lot for me. Is it possible to reduce this value by half, for example, 64? Thanks!

**Comment by ostaquet** [comment]
The size of the internal buffer depends mainly on the URL length . If your URL is not too long, 64 bytes should work. The best is to test the different size and see when it is too small.
